django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('study_tracker.urls')),
]

study_tracker/urls.py
from django.urls import path
from study_tracker.views import show_tracker, create_assignment, show_json, show_xml, register
from study_tracker.views import login_user, logout_user

app_name = 'study_tracker'

urlpatterns = [
    path('', show_tracker, name='show_tracker'),
    path('create/', create_assignment, name='create_assignment'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

study_tracker/models.py
from django.db import models


# Create your models here.

class Assignment(models.Model):
    name = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    progress = models.IntegerField()
    description = models.TextField()

study_tracker/forms.py
from django.forms import ModelForm
from study_tracker.models import Assignment

class AssignmentRecordForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ["name", "subject", "progress", "description"]

study_tracker/views.py
from django.shortcuts import render
from study_tracker.models import Assignment
from django.http import HttpResponseRedirect, HttpResponse
from study_tracker.forms import AssignmentRecordForm
from django.urls import reverse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime

# Create your views here.

@login_required(login_url='/tracker/login/')
def show_tracker(request):
    assignment_data = Assignment.objects.all()
    context = {
        'list_of_assignments': assignment_data,
        'name' :request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "tracker.html", context)

def create_assignment(request):
    form = AssignmentRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('study_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "create_assignment.html", context)

def show_xml(request):
    data = Assignment.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Assignment.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('study_tracker:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("study_tracker:show_tracker")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('study_tracker:login'))
    response.delete_cookie('last_login')
    return response

study_tracker/templates/create_assignment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Tambah Tugas Baru</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Tambah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

study_tracker/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'study_tracker:register' %}">Buat Akun</a>

</div>

{% endblock content %}

study_tracker/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

study_tracker/templates/tracker.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Study Tracker</span>
        <span class="navbar-text">
            Sesi terakhir login: {{ last_login }}
        </span>
        <a href="{% url 'study_tracker:logout' %}">
            <button class="btn btn-outline-danger me-2" type="button">Logout</button>
        </a>
    </div>
</nav>

<h5>Nama: </h5>
<p>{{name}}</p>

<table>
    <tr>
        <th>Nama</th>
        <th>Subjek</th>
        <th>Tanggal</th>
        <th>Progres</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for assignment in list_of_assignments %}
    <tr>
        <td>{{assignment.name}}</td>
        <td>{{assignment.subject}}</td>
        <td>{{assignment.date}}</td>
        <td>{{assignment.progress}}</td>
        <td>{{assignment.description}}</td>
    </tr>
    {% endfor %}
</table>

</table>

<br>
<a href="{% url 'study_tracker:create_assignment' %}">
    <button>
        Tugas Baru
    </button>
</a>

<br><br>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<a href="{% url 'study_tracker:logout' %}">
    <button>
        Logout
    </button>
</a>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
{% block meta %}
{% endblock meta %}
</head>

<body>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>